### PR TITLE
Removed that terrible link

### PR DESCRIPTION
**Pull request by Dasonk**
Clearly this link needs to be removed

### CODE REVIEW

**Comment by trinker** [comment]
Such anger towards @bryangoodrich  What a bot thing to do.

**Comment by Dasonk** [comment]
The pull request is still open.  I'm still hoping it gets accepted!!!

**Comment by Dasonk** [comment]
This could probably be closed now

**Comment by bryangoodrich** [comment]
I hate you all.

**Comment by Dasonk** [comment]
Aww. That's the nicest thing you've ever said to me.

**Pull request closed without merging**
